"""empty message

Revision ID: 20a9bf13f901
Revises: a4c9a62b0536
Create Date: 2018-10-11 15:24:53.552592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a9bf13f901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('designdetails', 'mask', type_=sa.Text(), nullable=True)
    op.alter_column('recipe_details', 'name', type_=sa.Text(), nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_headers', 'active2p')
    # ### end Alembic commands ###
